#!/bin/bash

die () {
    echo >&2 "$@"
    exit 1
}

APP_NAME=$1
APP_DIR="/data/vhost/"$1

#sanity check
[ "$#" -eq 1 ] || die "1 arguments required, $# provided"

#create directory
mkdir $APP_DIR
cd $APP_DIR

#setup virtual environemnt
virtualenv $APP_DIR
source $APP_DIR"/bin/activate"

#install django
pip install django==1.3

#create django instance
django-admin.py startproject $APP_NAME

#remove existing settings file
rm $APP_DIR"/"$APP_NAME"/settings.py"

#create local settings file
#------------------------------------------------------------------
cat >> $APP_DIR"/"$APP_NAME"/local_settings.py" << EOF
#debug
DEBUG = True
TEMPLATE_DEBUG = DEBUG

#database
DATABASE_ENGINE = 'mysql'
DATABASE_NAME = '$APP_NAME'
DATABASE_USER = 'root'
DATABASE_PASSWORD = ''
DATABASE_HOST = ''
DATABASE_PORT = ''

PROJECT_DIR = '$APP_DIR/$APP_NAME'

# Absolute path to the directory that holds media.
MEDIA_ROOT = PROJECT_DIR + '/media'
ADMIN_MEDIA_ROOT = PROJECT_DIR + '/media'

# templates
TEMPLATE_DIRS = (
    PROJECT_DIR + "/templates"
)

#admins
ADMINS = (
    # ('Your Name', 'your_email@domain.com'),
)
MANAGERS = ADMINS
EOF
#------------------------------------------------------------------

#create settings file
#------------------------------------------------------------------
cat >> $APP_DIR"/"$APP_NAME"/settings.py" << EOF
TIME_ZONE = 'Europe/London'
LANGUAGE_CODE = 'en-gb'
SITE_ID = 1
CAMPAIGN_ID = 1
USE_I18N = True
MEDIA_URL = '/site-media/'

ADMIN_MEDIA_PREFIX = '/admin-media/'

TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.load_template_source',
    'django.template.loaders.app_directories.load_template_source',
)

AUTHENTICATION_BACKENDS = (
    "clortho.auth_backends.FacebookBackend",
)

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.contrib.auth.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.media",
    'django.core.context_processors.request',
    'django.contrib.auth.context_processors.auth',
)

MIDDLEWARE_CLASSES = (
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
)

ROOT_URLCONF = 'urls'

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.flatpages',
    'main',
)

try:
    from local_settings import *
except ImportError:
    print "Missing local_settings.py file or file not in PATH"
EOF
#------------------------------------------------------------------

#Create default django folder structure
mkdir $APP_DIR"/"$APP_NAME"/templates"
mkdir $APP_DIR"/"$APP_NAME"/templates/main"
mkdir $APP_DIR"/"$APP_NAME"/media"
mkdir $APP_DIR"/"$APP_NAME"/media/css"
mkdir $APP_DIR"/"$APP_NAME"/media/images"
mkdir $APP_DIR"/"$APP_NAME"/media/javascript"

#add default files
touch $APP_DIR"/"$APP_NAME"/media/javascript/main.js"
#-----------------------------------------------------------
cat >> $APP_DIR/$APP_NAME/templates/main/base.html << EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.1/build/reset/reset-min.css">
	    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/main.css" />
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
	    <title>{% block title %}{% endblock %} | $APP_NAME</title>
	</head>
	<body>
	    {# Header #}
	    <div id="divHeader">
	        <div>
    	        <h1><a href="/"><span>$APP_NAME</span></a></h1>
    	        {# menu #}
    	        <ul id="ulMenu">
    	           <li><a href="/">Home</a></li>
    	        </ul>
	        </div>
	    </div>
		<div id="divPage">
		    {# Errors #}
	        <div id="divErrors">
	            {% if error_messages %}
                 <ul>
                     {% for error in error_messages %}
                         <li>{{ error|escape }}</li>
                     {% endfor %}
                 </ul>
                 {% endif %}
		         {% block errors %}

		         {% endblock %}		    
		     </div>
		     
    	    {# Content #}
    	    <div id="divContent">      
    		    {% block content %}{% endblock %}
    	    </div>			
    	</div>
    	{% block footer %}
			<div id="divFooter">
    	        <ul>
    	           <li><a href="/">Home</a></li>
    	        </ul>
			</div>
		{% endblock %}
		
		{# Script #}
	    <script type="text/javascript" defer="defer">
	        {% block run_script %}{% endblock %}
        </script>
	</body>
</html>

EOF
#-----------------------------------------------------------
cat >> $APP_DIR/$APP_NAME/templates/main/index.html << EOF
{% extends "main/base.html" %}
{% block title %}Welcome{% endblock %}
{% block content %}
    <h2>Hello!</h2>
{% endblock %}
EOF
#-----------------------------------------------------------

#Create main django app
python $APP_NAME/manage.py startapp main

#-----------------------------------------------------------
rm $APP_DIR/$APP_NAME/main/views.py
cat >> $APP_DIR/$APP_NAME/main/views.py << EOF
from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404
from django.template import RequestContext
import models 

def index(request):
    data= {}
    return render_to_response('main/index.html', data, context_instance = RequestContext(request))
EOF
#-----------------------------------------------------------
rm $APP_DIR/$APP_NAME/urls.py
cat >> $APP_DIR/$APP_NAME/urls.py << EOF
from django.contrib import admin
from django.conf.urls.defaults import *
from main import views as main_views
import settings

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', main_views.index, name='index'),
    (r'^admin/', include(admin.site.urls)),    
    url(r'^site-media/(?P<path>.*)$',       'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),    
    url(r'^admin-media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.ADMIN_MEDIA_ROOT, 'show_indexes':True}),        

)
EOF
#-----------------------------------------------------------
cat >> $APP_DIR/$APP_NAME/media/css/main.css << EOF
html {margin:0; padding:0;}
body {text-align:center;margin:0;padding:0; font-family:helvetica, arial, sans-serif;}
#divHeader div, #divPage {width:900px; text-align:left;margin:0 auto;position:relative;} 

/* header */
#divHeader {background:#1a1a1a; border-bottom:solid 10px #4d4d4d;  padding:0.5em;}
#divHeader h1 {font-size:2em;}
#divHeader a {color:#fff;}
#ulMenu li {display:inline;}

/* page */
#divPage {padding:2em 0;}
#divContent {min-height:20em;}

#divFooter {background:#1a1a1a; border-top:solid 20px #4d4d4d;
    padding-top:2em; padding-bottom:1em; color:#fff; font-size:0.8em;}
#divFooter a {color:#fff;}
EOF
#-----------------------------------------------------------

#install other packages
pip install mysql-python

#setup database
echo  'create schema '$APP_NAME | mysql -uroot


#sync DB
python $APP_NAME/manage.py syncdb