#!/bin/bash

die () {
    echo >&2 "$@"
    exit 1
}

APP_NAME=$1
APP_DIR="/Users/richardpope/code/"$1

#sanity check
[ "$#" -eq 1 ] || die "1 arguments required, $# provided"

#create directory
mkdir $APP_DIR
cd $APP_DIR

#setup virtual environemnt
virtualenv $APP_DIR
source $APP_DIR"/bin/activate"

#install django
pip install django==1.5.4

#install other packages
pip install psycopg2
pip install dj-database-url
pip install south==0.8.2

#create django instance
django-admin.py startproject $APP_NAME

#remove existing settings file
rm $APP_DIR"/"$APP_NAME"/"$APP_NAME"/settings.py"

#------------------------------------------------------------------
cat >> $APP_DIR"/Procfile" << EOF
web: python $APP_NAME/manage.py runserver 0.0.0.0:\$PORT --noreload
EOF
#------------------------------------------------------------------

#create local settings file
#------------------------------------------------------------------
cat >> $APP_DIR"/"$APP_NAME"/"$APP_NAME"/local_settings.py" << EOF
#debug
DEBUG = True
TEMPLATE_DEBUG = DEBUG

#database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': '$APP_NAME',
        'USER': 'richardpope',
        'HOST': '',
        'PASSWORD': '',
    }
}

EOF
#------------------------------------------------------------------

#create settings file
#------------------------------------------------------------------
cat >> $APP_DIR"/"$APP_NAME"/"$APP_NAME"/settings.py" << EOF
import os
import dj_database_url
TIME_ZONE = 'Europe/London'
LANGUAGE_CODE = 'en-gb'
SITE_ID = 1
CAMPAIGN_ID = 1
USE_I18N = True
MEDIA_URL = '/site-media/'

ADMIN_MEDIA_PREFIX = '/admin-media/'

TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
)


TEMPLATE_CONTEXT_PROCESSORS = (
    "django.contrib.auth.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.media",
    'django.core.context_processors.request',
    'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',
)

MIDDLEWARE_CLASSES = (
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
)

ROOT_URLCONF = '$APP_NAME.urls'

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',]'django.contrib.staticfiles',
    'south',
    'main',
)

#database
DATABASES = {'default': dj_database_url.config(default='postgres://localhost')}

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))

#key
SECRET_KEY = 'changethis'

# Absolute path to the directory that holds media.
MEDIA_ROOT = PROJECT_DIR + '/media'
STATIC_URL = PROJECT_DIR + '/media/'
ADMIN_MEDIA_ROOT = PROJECT_DIR + '/media'

# templates
TEMPLATE_DIRS = (
    PROJECT_DIR + "/templates"
)

#admins
ADMINS = (
    # ('Your Name', 'your_email@domain.com'),
)
MANAGERS = ADMINS

try:
    from local_settings import *
except ImportError:
    pass
EOF
#------------------------------------------------------------------

#Create default django folder structure
mkdir $APP_DIR"/"$APP_NAME"/templates"
mkdir $APP_DIR"/"$APP_NAME"/templates/main"
mkdir $APP_DIR"/"$APP_NAME"/media"
mkdir $APP_DIR"/"$APP_NAME"/media/css"
mkdir $APP_DIR"/"$APP_NAME"/media/images"
mkdir $APP_DIR"/"$APP_NAME"/media/javascript"

#add default files
touch $APP_DIR"/"$APP_NAME"/media/javascript/main.js"
touch $APP_DIR"/TODO.txt"
touch $APP_DIR"/README.md"

#-----------------------------------------------------------
cat >> $APP_DIR/$APP_NAME"/media/css/main.css" << EOF
body {
    padding-top:60px;
}
EOF
#-----------------------------------------------------------


#-----------------------------------------------------------
cat >> $APP_DIR/requirements.txt << EOF
Django==1.5.4
psycopg2==2.4.2
dj-database-url
south==0.8.2
EOF
#-----------------------------------------------------------

#-----------------------------------------------------------
cat >> $APP_DIR/$APP_NAME/templates/main/base.html << EOF
<!doctype html>
<html>
<head>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="shortcut icon" href="{{ MEDIA_URL }}/images/favicon.ico"/>
      <script type="text/javascript" src="http://codeorigin.jquery.com/jquery-2.0.3.min.js"></script>
      <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
      <script type="text/javascript" src="{{ MEDIA_URL }}/javascript/main.js"></script>
      <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
      <link rel="stylesheet" href="{{ MEDIA_URL }}/css/main.css">
	  <title>{% block title %}{% endblock %} | $APP_NAME</title>
	</head>
	<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">$APP_NAME</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}">Home</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
	</body>
</html>

EOF
#-----------------------------------------------------------
cat >> $APP_DIR/$APP_NAME/templates/main/index.html << EOF
{% extends "main/base.html" %}
{% block title %}Welcome{% endblock %}
{% block content %}
    <h1>$APP_NAME</h1>
{% endblock %}
EOF
#-----------------------------------------------------------

#Create main django app
python $APP_NAME/manage.py startapp main

#-----------------------------------------------------------
rm $APP_DIR/main/views.py
cat >> $APP_DIR/main/views.py << EOF
from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404
from django.template import RequestContext
import models

def index(request):
    data= {}
    return render_to_response('main/index.html', data, context_instance = RequestContext(request))
EOF
#-----------------------------------------------------------
rm $APP_DIR/$APP_NAME/$APP_NAME/urls.py
cat >> $APP_DIR/$APP_NAME/$APP_NAME/urls.py << EOF
from django.contrib import admin
from django.conf.urls.defaults import *
from main import views as main_views
from $APP_NAME import settings

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', main_views.index, name='index'),
(r'^admin/', include(admin.site.urls)),
    url(r'^site-media/(?P<path>.*)$',       'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
    url(r'^admin-media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.ADMIN_MEDIA_ROOT, 'show_indexes':True}),

)
EOF

#------------------------------------------------------------------
cat >> $APP_DIR"/.gitignore" << EOF
bin
include
lib
.Python
*.pyc
$APP_NAME/local_settings.py
EOF
#------------------------------------------------------------------

#setup database
echo  'create database '$APP_NAME | psql

#sync DB
python $APP_NAME/manage.py syncdb
python $APP_NAME/manage.py schemamigration main --initial
python $APP_NAME/manage.py migrate main

#setup git
cd $APP_DIR
# git init .

# # #send to heroku
# heroku create
# git add .
# git commit -m "init"
# git push heroku master
# heroku addons:add heroku-postgresql:dev
# heroku ps:scale web=1
# heroku run python $APP_NAME/manage.py syncdb
# heroku run python $APP_NAME/manage.py migrate main

